language: go

install:
  - go get golang.org/x/crypto/bcrypt
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega

script:
  - ginkgo -r -race ./password

go:
  - 1.5
  - 1.6
  - tip
